// vuejs-frontend/src/components/NavBar.vue
<template>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="container">
      <router-link class="navbar-brand" to="/">BookMarker</router-link>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <!--
          <li class="nav-item">
            <router-link class="nav-link" to="/">Home</router-link>
          </li>
          -->
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item" v-if="isUserLoggedIn">
            <router-link class="nav-link" to="/newBookmark">Add Bookmark</router-link>
          </li>
          <li class="nav-item" v-if="!isUserLoggedIn">
            <router-link class="nav-link" to="/login">Login</router-link>
          </li>
          <li class="nav-item" v-if="isUserLoggedIn" >
            <a class="nav-link" href="#" @click.prevent="doLogout">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</template>

<script>
export default {
  name: 'NavBar',
  data () {
    return {
      loggedIn: false
    }
  },
  created: function () {
    const accessToken = localStorage.getItem('access_token')
    if (accessToken) {
      this.loggedIn = true
    }
    var self = this

    window.eventBus.$on('loggedin', function () {
      self.loggedIn = true
    })

    window.eventBus.$on('logout', function () {
      console.log('received logout emit event')
      self.loggedIn = false
      self.$store.dispatch('logout')
      self.$router.push('/login')
    })
  },

  methods: {
    doLogout () {
      window.eventBus.$emit('logout')
    }
  },

  computed: {
    isUserLoggedIn () {
      return this.loggedIn
    }
  }
}
</script>

// bookmarker-ui-react/src/components/Layout/NavBar.js
import React from "react";
import { useSelector } from "react-redux";
import { NavLink } from "react-router-dom";
import { cleanState } from "../../store/localStorage";

const NavBar = () => {
    const user = useSelector(state => state.user);

    const logoutHandler = () => {
        cleanState();
        window.location = "/login";
    };

    let authenticatedLinks;

    if (user.access_token) {
        authenticatedLinks = (
            <ul className="navbar-nav">
                <li className="nav-item">
                    <NavLink className="nav-link" to="/add-bookmark">
                        Add Bookmark
                    </NavLink>
                </li>
                <li className="nav-item">
                    <NavLink className="nav-link" to="/login" onClick={logoutHandler}>
                        Logout
                    </NavLink>
                </li>
            </ul>
        );
    } else {
        authenticatedLinks = (
            <ul className="navbar-nav">
                <li className="nav-item">
                    <NavLink className="nav-link" to="/login">
                        Login
                    </NavLink>
                </li>
            </ul>
        );
    }
    return (
        <nav className="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <NavLink className="navbar-brand" to="/">
                Bookmarker
            </NavLink>
            <button
                className="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarCollapse"
                aria-controls="navbarCollapse"
                aria-expanded="false"
                aria-label="Toggle navigation"
            >
                <span className="navbar-toggler-icon"></span>
            </button>
            <div className="collapse navbar-collapse" id="navbarCollapse">
                <ul className="navbar-nav mr-auto">
                    {/*
                    <li className="nav-item">
                        <NavLink className="nav-link" to="/">
                            Home <span className="sr-only">(current)</span>
                        </NavLink>
                    </li>*/}
                </ul>
                {authenticatedLinks}
            </div>

        </nav>
    );
};

export default NavBar;
